server:
  port: 8082

spring:
  application:
    name: CLIENT-SERVICE


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: lP2RcjBBN3dYIorv7tYPacRfC50FGEG4
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/keycloak"
      provider:
        keycloak:
          issuer-uri: http://keycloak:8080/realms/microfinance-realm







eureka:
  client:
    serviceUrl:
      defaultZone: http://register:8761/eureka/



  instance:
    prefer-ip-address: true
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8082"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG