server:
  port: 8082

spring:
  application:
    name: client-SERVICE
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8082"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
