server:
  port: 8086

spring:
  application:
    name: LOAN-SERVICE


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: GPPofSny6rec6h69mS4h7f6UDkFbXQza
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8086/login/oauth2/code/keycloak"

        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/microfinance-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8086"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=banque;encrypt=true;trustServerCertificate=true
    username: API
    password: SA@1T3CH
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.springframework: DEBUG
