server:
  port: 8086

spring:
  application:
    name: LOAN-SERVICE


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: lP2RcjBBN3dYIorv7tYPacRfC50FGEG4
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8086/login/oauth2/code/keycloak86"
      provider:
        keycloak:
          issuer-uri: http://keycloak:8080/realms/microfinance-realm




  instance:
    prefer-ip-address: true
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8086"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=banque;encrypt=true;trustServerCertificate=true
    username: API
    password: SA@1T3CH
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.springframework: DEBUG
