server:
  port: 8083

spring:
  application:
    name: Users-services
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8083"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
