spring:
 cloud:
   gateway:
     routes:
       - id: users-services
         uri: lb://USERS-SERVICES
         predicates:
           - Path=/users/**
         filters:
           - AuthenticationFilter

       - id: transaction-services
         uri: lb://TRANSACTION-SERVICES
         predicates:
           - Path=/transactions/**
         filters:
           - AuthenticationFilter

       - id: reporting-services
         uri: lb://REPORTING-SERVICES
         predicates:
           - Path=/reports/**
         filters:
           - AuthenticationFilter

       - id: loans-services
         uri: lb://LOAN-SERVICE
         predicates:
           - Path=/loan/**
         filters:
           - AuthenticationFilter

       - id: client-services
         uri: lb://CLIENT-SERVICE
         predicates:
           - Path=/client/**
         filters:
           - AuthenticationFilter

       - id: authentification-services
         uri: lb://AUTHENTICATION-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: Api-gateway
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/