spring:
 cloud:
   gateway:
     routes:
       - id: users-services
         uri:  http://localhost:8083
         predicates:
           - Path=/users/**
         filters:
           - AuthenticationFilter

       - id: transaction-services
         uri:  http://localhost:8084
         predicates:
           - Path=/transactions/**
         filters:
           - AuthenticationFilter

       - id: reporting-services
         uri:  http://localhost:8085
         predicates:
           - Path=/reports/**
         filters:
           - AuthenticationFilter

       - id: loans-services
         uri:  http://localhost:8086
         predicates:
           - Path=/loan/**
         filters:
           - AuthenticationFilter

       - id: client-services
         uri:  http://localhost:8082
         predicates:
           - Path=/client/**
         filters:
           - AuthenticationFilter

       - id: authentification-services
         uri:  http://localhost:8081
         predicates:
           - Path=/auth/**

 application:
   name: Api-gateway
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/