server:
  port: 8080

spring:
  application:
    name: api-gateway

  management:
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /actuator

  cloud:
    gateway:
      routes:
        # Clients Service
        - id: clients-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

        # Users Service
        - id: users-services
          uri: lb://USERS-SERVICES
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

        # Transactions Service
        - id: transactions-service
          uri: lb://TRANSACTION-SERVICES
          predicates:
            - Path=/transactions/**
          filters:
            - RewritePath=/transactions/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

        # Reporting Service
        - id: reporting-services
          uri: lb://REPORTING-SERVICES
          predicates:
            - Path=/reports/**
          filters:
            - RewritePath=/reports/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

        # Loans Service
        - id: loans-services
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**
          filters:
            - RewritePath=/loan/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

        # Auth Service
        - id: auth-services
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs  # Fix for Swagger UI

# SPRINGDOC CONFIGURATION (Swagger UI for All Services via API Gateway)
springdoc:
  swagger-ui:
    urls:
      - name: Clients Service
        url: /client/v3/api-docs
      - name: Users Service
        url: /users/v3/api-docs
      - name: Transactions Service
        url: /transactions/v3/api-docs
      - name: Reporting Service
        url: /reports/v3/api-docs
      - name: Loans Service
        url: /loan/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
    path: /swagger-ui.html

  api-docs:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
