server:
  port: 8080

spring:
  application:
    name: api-gateway
  management:
    health:
      status:
        show-details: always  # Display more detailed health status
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /actuator
    webflux:
      cors:
        allowed-origins:
          - "http://localhost:8080"
          - "http://localhost:8081"
          - "http://localhost:8082"
          - "http://localhost:8083"
          - "http://localhost:8084"
          - "http://localhost:8085"
          - "http://localhost:8086"
        allowed-methods: "GET, POST, PUT, DELETE"
        allowed-headers: "*"
        allow-credentials: true

  cloud:
    gateway:
      routes:
        # Clients Service
        - id: clients-service
          uri: http://localhost:8082
          predicates:
            - Path=/client/**
            - Path=/client/v3/api-docs
          filters:
            - RewritePath=/client/v3/api-docs, /v3/api-docs
            - RewritePath=/client/(?<remaining>.*), /$\{remaining}  # Corrected rewrite for client endpoints

        # Users Service
        - id: users-services
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
            - Path=/users/v3/api-docs
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs
            - RewritePath=/users/(?<remaining>.*), /$\{remaining}  # Corrected rewrite for users endpoints

        # Transactions Service
        - id: transactions-service
          uri: http://localhost:8084
          predicates:
            - Path=/transactions/**
            - Path=/transactions/v3/api-docs
          filters:
            - RewritePath=/transactions/v3/api-docs, /v3/api-docs
            - RewritePath=/transactions/(?<remaining>.*), /$\{remaining}  # Corrected rewrite for transactions endpoints

        # Reporting Service
        - id: reporting-services
          uri: http://localhost:8085
          predicates:
            - Path=/reports/**
            - Path=/reports/v3/api-docs
          filters:
            - RewritePath=/reports/v3/api-docs, /v3/api-docs
            - RewritePath=/reports/(?<remaining>.*), /$\{remaining}  # Corrected rewrite for reports endpoints

        # Loans Service
        - id: loans-services
          uri: http://localhost:8086
          predicates:
            - Path=/loan/**
            - Path=/loan/v3/api-docs
          filters:
            - RewritePath=/loan/v3/api-docs, /v3/api-docs
            - RewritePath=/loan/(?<remaining>.*), /$\{remaining}  # Corrected rewrite for loans endpoints

        # Auth Service
        - id: auth-services
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs
            - RewritePath=/auth/(?<remaining>.*), /$\{remaining}  # Fixed the rewrite for auth service

springdoc:
  swagger-ui:
    urls:
      - name: Clients Service
        url: /client/v3/api-docs
      - name: Users Service
        url: /users/v3/api-docs
      - name: Transactions Service
        url: /transactions/v3/api-docs
      - name: Reporting Service
        url: /reports/v3/api-docs
      - name: Loans Service
        url: /loan/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs
    path: /swagger-ui.html

  api-docs:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
