server:
  port: 8080

spring:
  application:
    name: api-gateway



  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: lP2RcjBBN3dYIorv7tYPacRfC50FGEG4
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak80"
      provider:
        keycloak:
          issuer-uri: http://keycloak:8080/realms/microfinance-realm




  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8083"
        - "http://localhost:8082"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true


  management:
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /actuator

  cloud:
    gateway:
  default-filters:
    - name: RequestRateLimiter
      args:
        redis-rate-limiter.replenishRate: 20  # Number of tokens added per second
        redis-rate-limiter.burstCapacity: 20  # Maximum burst capacity
        redis-rate-limiter.requestedTokens: 1  # Number of tokens consumed per request
        key-resolver: "#{@userKeyResolver}"
      routes:
        # Clients Service
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/v3/api-docs, /v3/api-docs  # Fix for Swagger UI
            - AddRequestHeader=X-Forwarded-Prefix, /client
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1

        # Users Service
        - id: users-services
          uri: lb://USERS-SERVICES
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/v3/api-docs, /v3/api-docs  # Fix for Swagger UI
            #  - AddRequestHeader=X-Forwarded-Prefix, /users
            - RewritePath=/client/(?<remaining>.*), /${remaining}
            - AddRequestHeader=X-Forwarded-Prefix, /client
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        # Transactions Service
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICES
          predicates:
            - Path=/transactions/**
          filters:
            - RewritePath=/transactions/v3/api-docs, /v3/api-docs  # Fix for Swagger UI
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        # Reporting Service
        - id: reporting-services
          uri: lb://REPORTING-SERVICES
          predicates:
            - Path=/reports/**
          filters:
            - RewritePath=/reports/v3/api-docs, /v3/api-docs  # Fix for Swagger UI
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        # Loans Service
        - id: loans-services
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**
          filters:
            - RewritePath=/loan/v3/api-docs, /v3/api-docs  # Fix for Swagger
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

        # Auth Service
        - id: auth-services
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs  # Fix for Swagger UI
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1


# SPRINGDOC CONFIGURATION (Swagger UI for All Services via API Gateway)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Clients Service
        url: /client/v3/api-docs
      - name: Users Service
        url: /users/v3/api-docs
      - name: Transactions Service
        url: /transactions/v3/api-docs
      - name: Reporting Service
        url: /reports/v3/api-docs
      - name: Loans Service
        url: /loan/v3/api-docs
      - name: Auth Service
        url: /auth/v3/api-docs


  api-docs:
    enabled: true
    path: /v3/api-docs
    swagger-ui:
      enabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG

