package com.microfinance.client_services.models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "COLLECTEUR")
@Schema(description = "Class Collecteur for collector information")
public class Collecteur {

    @Schema(description = "The unique ID of the collector (12 characters)")
    @Id
    @Column(name = "num", nullable = false, length = 12)
    private String num;

    @Schema(description = "The name of the collector (maximum 30 characters)")
    @Column(name = "nom", nullable = false, length = 30)
    private String nom;

    @Schema(description = "The address of the collector (maximum 50 characters)")
    @Column(name = "adresse", length = 50)
    private String adresse;

    @Schema(description = "The commission value assigned to the collector")
    @Column(name = "commission", nullable = false)
    private float commission;

    @Schema(description = "The commission rate applicable to the collector")
    @Column(name = "tauxcom")
    private Float tauxcom;

    @Schema(description = "The bonus rate applicable to the collector")
    @Column(name = "tauxPrime")
    private Float tauxPrime;

    @Schema(description = "The collector's national identity number (CNI)")
    @Column(name = "cni", nullable = false, length = 50)
    private String cni;

    @Schema(description = "The collector's account number (maximum 25 characters)")
    @Column(name = "numcpt", length = 25)
    private String numcpt;

    @Schema(description = "The collector's earned bonus value")
    @Column(name = "prime")
    private Float prime;

    @Schema(description = "The collector's password for authentication (maximum 50 characters)")
    @Column(name = "password", nullable = false, length = 50)
    private String password;

    @Schema(description = "The geographical location of the collector")
    @Column(name = "localisation", nullable = false, length = 50)
    private String localisation;

    @Schema(description = "The code assigned to the collector for identification")
    @Column(name = "codage", nullable = false, length = 12)
    private String codage;

    @Schema(description = "The front-side ID image path or URL")
    @Column(name = "idFront", length = 255)
    private String idFront;

    @Schema(description = "The back-side ID image path or URL")
    @Column(name = "idBack", length = 255)
    private String idBack;

    @Schema(description = "The total revenue generated by the collector")
    @Column(name = "chiffreAffaire")
    private Float chiffreAffaire;

    @Schema(description = "The collector's phone number (maximum 15 characters)")
    @Column(name = "tel", length = 15)
    private String tel;

    @Schema(description = "The path or URL to the collector's profile picture")
    @Column(name = "picture", length = 255)
    private String picture;

    @Schema(description = "Indicates whether the collector is activated")
    @Column(name = "isActivated")
    private Boolean isActivated;

    @Schema(description = "Indicates whether the collector is in debit")
    @Column(name = "Isdebit")
    private Integer isDebit;

    @Schema(description = "Indicates whether the collector is in credit")
    @Column(name = "Iscredit")
    private Integer isCredit;

    @Schema(description = "Indicates whether the collector is connected")
    @Column(name = "Isconnect")
    private Integer isConnect;

    @Schema(description = "Indicates whether the collector's account is locked")
    @Column(name = "Islocked")
    private Integer isLocked;

    @Schema(description = "The date the collector's account was created")
    @Column(name = "dateCrea")
    private Date dateCrea;

    @Schema(description = "The blocked amount in the collector's account")
    @Column(name = "MntBlk")
    private Float mntBlk;

    @Schema(description = "The phone number for blocked SMS notifications (maximum 15 characters)")
    @Column(name = "TelBlkSMS", length = 15)
    private String telBlkSMS;

    @Schema(description = "The MAC address of the collector's device")
    @Column(name = "MacAdd", length = 50)
    private String macAdd;

    @Schema(description = "Indicates whether the collector is working offline")
    @Column(name = "ISOFFLINE")
    private Boolean isOffline;

    @Schema(description = "The last operation number performed by the collector (maximum 20 characters)")
    @Column(name = "LastNumOp", length = 20)
    private String lastNumOp;

    @Schema(description = "The member account number linked to the collector")
    @Column(name = "NUMCPTMBR", length = 50)
    private String numCptMbr;

    @Schema(description = "Indicates whether the collector is using the default password")
    @Column(name = "defaultPwd", length = 1)
    private String defaultPwd;

    @Schema(description = "The current balance in the collector's account")
    @Column(name = "soldeActuel", precision = 18, scale = 0)
    private Float soldeActuel;

    @Schema(description = "The secret key used for encryption or authentication (not persisted in the database)")
    @Transient
    private String Key;

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public float getCommission() {
        return commission;
    }

    public void setCommission(float commission) {
        this.commission = commission;
    }

    public Float getTauxcom() {
        return tauxcom;
    }

    public void setTauxcom(Float tauxcom) {
        this.tauxcom = tauxcom;
    }

    public Float getTauxPrime() {
        return tauxPrime;
    }

    public void setTauxPrime(Float tauxPrime) {
        this.tauxPrime = tauxPrime;
    }

    public String getCni() {
        return cni;
    }

    public void setCni(String cni) {
        this.cni = cni;
    }

    public String getNumcpt() {
        return numcpt;
    }

    public void setNumcpt(String numcpt) {
        this.numcpt = numcpt;
    }

    public Float getPrime() {
        return prime;
    }

    public void setPrime(Float prime) {
        this.prime = prime;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLocalisation() {
        return localisation;
    }

    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }

    public String getCodage() {
        return codage;
    }

    public void setCodage(String codage) {
        this.codage = codage;
    }

    public String getIdFront() {
        return idFront;
    }

    public void setIdFront(String idFront) {
        this.idFront = idFront;
    }

    public String getIdBack() {
        return idBack;
    }

    public void setIdBack(String idBack) {
        this.idBack = idBack;
    }

    public Float getChiffreAffaire() {
        return chiffreAffaire;
    }

    public void setChiffreAffaire(Float chiffreAffaire) {
        this.chiffreAffaire = chiffreAffaire;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Boolean getActivated() {
        return isActivated;
    }

    public void setActivated(Boolean activated) {
        isActivated = activated;
    }

    public Integer getIsDebit() {
        return isDebit;
    }

    public void setIsDebit(Integer isDebit) {
        this.isDebit = isDebit;
    }

    public Integer getIsCredit() {
        return isCredit;
    }

    public void setIsCredit(Integer isCredit) {
        this.isCredit = isCredit;
    }

    public Integer getIsConnect() {
        return isConnect;
    }

    public void setIsConnect(Integer isConnect) {
        this.isConnect = isConnect;
    }

    public Integer getIsLocked() {
        return isLocked;
    }

    public void setIsLocked(Integer isLocked) {
        this.isLocked = isLocked;
    }

    public Date getDateCrea() {
        return dateCrea;
    }

    public void setDateCrea(Date dateCrea) {
        this.dateCrea = dateCrea;
    }

    public Float getMntBlk() {
        return mntBlk;
    }

    public void setMntBlk(Float mntBlk) {
        this.mntBlk = mntBlk;
    }

    public String getTelBlkSMS() {
        return telBlkSMS;
    }

    public void setTelBlkSMS(String telBlkSMS) {
        this.telBlkSMS = telBlkSMS;
    }

    public String getMacAdd() {
        return macAdd;
    }

    public void setMacAdd(String macAdd) {
        this.macAdd = macAdd;
    }

    public Boolean getOffline() {
        return isOffline;
    }

    public void setOffline(Boolean offline) {
        isOffline = offline;
    }

    public String getLastNumOp() {
        return lastNumOp;
    }

    public void setLastNumOp(String lastNumOp) {
        this.lastNumOp = lastNumOp;
    }

    public String getNumCptMbr() {
        return numCptMbr;
    }

    public void setNumCptMbr(String numCptMbr) {
        this.numCptMbr = numCptMbr;
    }

    public String getDefaultPwd() {
        return defaultPwd;
    }

    public void setDefaultPwd(String defaultPwd) {
        this.defaultPwd = defaultPwd;
    }

    public Float getSoldeActuel() {
        return soldeActuel;
    }

    public void setSoldeActuel(Float soldeActuel) {
        this.soldeActuel = soldeActuel;
    }

    public String getKey() {
        return Key;
    }

    public void setKey(String key) {
        Key = key;
    }

    // Getters and setters (omitted for brevity)
}
