server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: TRANSACTION-SERVICES


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: GPPofSny6rec6h69mS4h7f6UDkFbXQza
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8084/login/oauth2/code/keycloak84"

        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/microfinance-realm

  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8084"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG