server:
  port: 8084


spring:
  application:
    name: TRANSACTION-SERVICES


  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: lP2RcjBBN3dYIorv7tYPacRfC50FGEG4
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8084/login/oauth2/code/keycloak84"
      provider:
        keycloak:
          issuer-uri: http://keycloak:8080/realms/microfinance-realm

  eureka:
    client:
      serviceUrl:
        defaultZone: http://register:8761/eureka/

    instance:
      prefer-ip-address: true
    webflux:
      cors:
        allowed-origins:
          - "http://localhost:8080"
          - "http://localhost:8083"
        allowed-methods: "GET,POST,PUT,DELETE"
        allowed-headers: "*"
        allow-credentials: true


  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
