server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: TRANSACTION-SERVICES
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8084"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
