server:
  port: 8084

spring:
  application:
    name: Transaction-Services
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8084"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
