spring:
  application:
    name: Authentication-SERVICE
  security:
    user:
      name: admin
      password: 1234

server:
  port: 8081

springdoc:
  swagger-ui:
    urls:
      - url: /auth/v3/api-docs
        name: authentification-services



