#spring:
#  application:
#    name: Authentication-services
##  security:
##    user:
##      name: admin
##      password: admin
#  webflux:
#    cors:
#      allowed-origins:
#        - "http://localhost:8080"
#        - "http://localhost:8081"
#      allowed-methods: "GET,POST,PUT,DELETE"
#      allowed-headers: "*"
#      allow-credentials: true
#server:
#  port: 8081
#
#springdoc:
#  api-docs:
#    enabled: true
#    path: /v3/api-docs  # Explicitly set API docs path
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    operations-sorter: alpha
#    tryItOutEnabled: true
#    display-request-duration: true
#    persist-authorization: true

server:
  port: 8088

spring:
  application:
    name: Authentication-services

  security:
    user:
     name: admin
     password: admin
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8088"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


