server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE


keycloak:
  auth-server-url: http://localhost:8180
  realm: microfinance-realm
  client-id: microfinance-client
  client-secret: GPPofSny6rec6h69mS4h7f6UDkFbXQza
  use-resource-role-mappings: true
  bearer-only: false
  ssl-required: none




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8081"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true




logging:
  level:
    org.springframework: DEBUG
