server:
  port: 8085

spring:
  application:
    name: REPORTING-SERVICES

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: microfinance-client
            client-secret: lP2RcjBBN3dYIorv7tYPacRfC50FGEG4
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8085/login/oauth2/code/keycloak85"

        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/microfinance-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  webflux:
    cors:
      allowed-origins:
        - "http://localhost:8080"
        - "http://localhost:8085"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true

#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG